version: '3.8'
services:
  frontend:
    container_name: flask-app
    image: jwearn1999/flask-app:latest
    build: ./front-end
    ports:
      - published: 80
        target: 5000
    deploy:
      replicas: 2

  service2-symbol-gen:
    container_name: symbol
    image: jwearn1999/symbol:latest
    build: ./cardvalue-api
    ports:
      - published: 5001
        target: 5000
    deploy:
      replicas: 2

  service3-suit-gen:
    container_name: suit
    image: jwearn1999/suit:latest
    build: ./cardsuit-api
    ports:
      - published: 5002
        target: 5000
    deploy:
      replicas: 2

  backend:
    container_name: card
    image: jwearn1999/card:latest
    build: ./card-api
    ports:
      - published: 5003
        target: 5000 
    deploy:
      replicas: 2  