version: "3.8"
services:
  mysql:
    image: jwearn1999/card-deck-db:latest
    build: ./db
    volumes:
      - type: volume
        source: card-vol
        target: /var/lib/mysql
    networks:
      - "card-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: card_db
  front-end:
    image: jwearn/card-deck-front:latest
    build: ./front-end
    networks:
      - "card-net"
    depends_on:
      - "mysql"
      - "cardvalue-api"
      - "cardsuit-api"
      - "card-api"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cardvalue-api:
    image: jwearn1999/card-cardvalue-api:latest
    build: ./cardvalue-api
    networks:
      - "card-net"
  cardsuit-api:
    image: jwearn1999/card-cardsuit-api:latest
    build: ./cardsuit-api
    networks:
      - "card-net"
  card-api:
    image: jwearn1999/card-card-api:latest
    build: ./card-api
    networks:
      - "card-net"
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - "card-net"
    depends_on:
      - "front-end"
volumes:
  card-vol:
networks:
  card-net: